app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('partner/', include('partner.urls')),
    path('course/', include('course.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path("list/", views.courseView, name= "course_view"),
    path("course-add/", views.courseAdd, name= "course_add"),
    path("course-edit/<str:pk>", views.courseEdit, name= "course_edit"),
    path("course-detail/<str:pk>", views.courseDetail, name= "course_detail"),
    path("course-section/", views.courseSection, name= "course_section"),
    path("list-section/", views.listSection, name= "list_section"),
    path("course-sub",views.courseSub, name="course_sub"),
    

   
]

partner/urls.py
from django.urls import path

from . import views

app_name = 'partner'

urlpatterns = [
    path("list/", views.partnerView, name= "partner_view"),
    path("partner-add/", views.partnerAdd, name= "partner_add"),
    path("partner-edit/<str:pk>", views.partnerEdit, name= "partner_edit"),

   
]

course/models.py
from django.db import models
from partner.models import Partner
from django.contrib.auth.models import User
import datetime
import os
from autoslug import AutoSlugField
# Create your models here.



Choi = (
    ('basic','basic'),
    ('medium','medium'),
    ('advanced','advanced'),
)

St = (
    ('draft','draft'),
    ('qurations','qurations'),
    ('publish','publish'),
    ('pending','pending'),
)
Lg = (
    ('en','english'),
    ('id','indonesia'),
)
Tc = (
    ('self','self-paced'),
    ('instructor','instructor-paced'),
)
Ct = (
    ('tecnologi','tecnologi'),
    ('law','law'),
    ('economic','economic'),
    ('social','social'),
    ('agriculture','agriculture'),
    ('mining','mining'),
    ('management','management'),
    ('program','program'),
)

def filepath(request, filename):
    old_filename = filename
    timeNow = datetime.datetime.now().strftime('%Y%m%d%H:%M:%S')
    filename = "%s%s" % (timeNow, old_filename)
    return os.path.join('course/', filename)



def current_year():
    return datetime.date.today().year

class Course (models.Model):
    course_name = models.CharField(max_length=250)
    topic = models.CharField(max_length=250)
    course_overview = models.TextField(null=True)
    category = models.CharField(max_length=50, choices=Ct,null=True)
    number_of_questions = models.IntegerField(null=True)
    time = models.IntegerField(help_text="durations of the quiz in minutes",null=True)
    required_score_to_pas = models.IntegerField("required score in %", null=True)
    level = models.CharField(max_length=10, choices=Choi, default='basic', null=True)
    status_course = models.CharField(max_length=10, choices=St, default='draft')
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    start_enrol = models.DateField(null=True)
    end_enrol = models.DateField(null=True)
    effort = models.CharField(max_length=20, null=True)
    lang = models.CharField(max_length=30, choices=Lg, default='id')
    org_partner = models.ForeignKey(Partner, on_delete=models.CASCADE)
    type_course = models.CharField(max_length=10, choices=Tc, default='self')
    image_course = models.ImageField(upload_to=filepath,null=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    course_year=models.IntegerField(null=True, default=current_year)

    def __str__(self):
        return f"{self.course_name} {self.status_course}"
    





    
class Category(models.Model):
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank = True, null=True)
    title = models.CharField(max_length=100) 
    slug = AutoSlugField(populate_from='title', unique=True, null=False, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    mk=models.ForeignKey(Course,on_delete=models.CASCADE,related_name='course_id')

    def __str__(self):
        return self.title

    class Meta:
        #enforcing that there can not be two categories under a parent with same slug
        
        # __str__ method elaborated later in post.  use __unicode__ in place of

        unique_together = ('slug', 'parent',)    
        verbose_name_plural = "categories"     

    def __str__(self):                           
        full_path = [self.title]                  
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' -> '.join(full_path[::-1])  

course/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.conf import settings
from .models import *
from django.contrib import messages
from django.db import connection
from django.db.models import Q
import json
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse,JsonResponse
import os


#course view
def courseView(request):
     if request.user.is_staff == True:
           course_list = Course.objects.all()
           partner_list = Partner.objects.all()
           user_list = User.objects.all()
           context = {'courselist':course_list,'partnerlist':partner_list,'userlist':user_list}   

           return render (request,'course_view.html', context)
     else:
          
        return redirect ('/')


#courseAdd

def courseAdd(request):

    if request.user.is_staff == True:
        if request.method == "POST":
                mk = Course()
                mk.course_name = request.POST.get('course_name')
                mk.topic = request.POST.get('topic')
                
                mk.level = request.POST.get('level')
                mk.status_course = request.POST.get('status_course')
               
                mk.org_partner_id = request.POST.get('org_partner')
                mk.type_course = request.POST.get('type_course')
                mk.image_course = request.POST.get('image_course')
                mk.author_id = request.POST.get('author')
                

                if len(request.FILES) != 0:
                    mk.image_course = request.FILES['image_course']
                    mk.save()
                    messages.success(request, "Create Courses  SUCCESSFULLY")
                    return redirect('/course/list')
        partner_list = Partner.objects.all()
        user_list = User.objects.all()
        context = {'userlist':user_list,'partnerlist':partner_list}
       
        return render (request,'course_add.html', context)
    else:
        
        return redirect ('/')

# coruse edit.
def courseEdit(request, pk):
    mk = Course.objects.get(id=pk)
    user_list = User.objects.all()
    if request.method == "POST":
        if len(request.FILES) != 0:
            if len(mk.image_course) > 0:
                os.remove(mk.image_course.path)
                 #prod.image = request.FILES['image']
            mk.image_course = request.FILES['image_course']
        mk.topic = request.POST.get('topic')

        mk.level = request.POST.get('level')
        mk.status_course = request.POST.get('status_course')

        mk.org_partner_id = request.POST.get('org_partner')
        mk.type_course = request.POST.get('type_course')
        #mk.image_course = request.POST.get('image_course')
        mk.author_id = request.POST.get('author')
        mk.save()
        messages.success(request, "Course Updated Successfully")
        return redirect('/course/list')

    context = {'course':mk,'user':user_list}
    return render(request, 'course_edit.html', context)

#course detail
def courseDetail(request, pk):
    if request.user.is_staff == True:
            mk = Course.objects.get(id=pk)

            catg = Category.objects.filter(parent=None, mk_id=mk)

            
            context = {'course':mk,'catg':catg}
        # print(catg)
            return render(request, 'course_detail.html', context)
    else:
          
        return redirect ('/')


#add section
@csrf_exempt
def courseSection(request):
    if request.user.is_staff == True:
             
       
        title = request.POST.get("title")
        mk = request.POST.get("mk_id")
        #print('id',course_section)
        try:
                
            vs = Category(title=title,
                         mk_id=mk)
            vs.save()
            ls = Category.objects.all().order_by( '-id')[:1].values()
            #ls = Section.objects.values()          
            section_data = list(ls)
            return JsonResponse({'status':'data section save','section_data':section_data})

        except:

            return JsonResponse({'status':'section no save'})
        

#add section
@csrf_exempt
def courseSub(request):
    if request.user.is_staff == True:
             
       
        title = request.POST.get("title")
        mk = request.POST.get("mk_id")
        parent = request.POST.get("parent_id")
        #print('id',course_section)
        try:
                
            vs = Category(title=title,
                         mk_id=mk,parent_id=parent)
            vs.save()
            ls = Category.objects.all().order_by( '-id')[:1].values()
            #ls = Section.objects.values()          
            section_data = list(ls)
            return JsonResponse({'status':'data sub save','section_data':section_data})

        except:

            return JsonResponse({'status':'sub section no save'})

    #list section
@csrf_exempt
def listSection(request):
    if request.user.is_staff == True:
           
      
        try:
            #mk = Course.objects.get(id=pk)
           

           
            ls = Section.objects.filter(section_id_course_id__isnull=True).values()
            #ls = Section.objects.values()          
            section_data = list(ls)
            print(section_data)
            return JsonResponse({'status':'200','section_data':section_data})

        except:

            return JsonResponse({'status':'404'})
                

#add sub section
@csrf_exempt
def courseSubSection(request):
    if request.user.is_staff == True:
             
       
        sub_section_name = request.POST.get("sub_section_name")
        sub_section_id_course = request.POST.get("sub_section_id_course")
        #print('id',course_section)
        try:
                
            vs = SubSection(sub_section_name=sub_section_name,
                         sub_section_id_course_id=sub_section_id_course)
            vs.save()
            ls = SubSection.objects.all().order_by( '-id')[:1].values()
            #ls = Section.objects.values()          
            sub_section_data = list(ls)
            return JsonResponse({'status':'data sub section save','sub_section_data':sub_section_data})

        except:

            return JsonResponse({'status':'sub section no save'})

course/templates/course_add.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

 
  <div class="row">
    <div class="col-md-12">
      <div class="tile">
        <h3 class="tile-title">Create new course</h3>
        <div class="tile-body">
          <form id="sumbitformpratner" method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">course name</label>
                    <input class="form-control" type="text" name="course_name" maxlength="250" required placeholder="Enter course name">
                  </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label"> topic</label>
                    <input class="form-control" type="text" name="topic" maxlength="250" required placeholder="Enter topic">
                  </div>
            </div>
           </div>
            <div class="row">
              <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">type </label>
                   
                <select class="form-control" name="type_course"  required>
                  <option>choice</option>
                  <option value="self">self</option>
                  <option value="instructor">instructor</option>
                 
                </select>
                </div>

                  
              </div>
              <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">org </label>
                   
                <select class="form-control" name="org_partner" required>
                  <option>-</option>
                  {% for part in partnerlist %}
                  <option value="{{part.id}}">{{part.partner_name}}</option>
                  {% endfor%}
                  
                 
                </select>
                </div>

                  
              </div>
            

              <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">status</label>
                    <select class="form-control" id="exampleSelect1" required name="status_course">
                      <option >select status</option>
                      <option value="draft">draft</option>
                    
                      <option value="pending">pending</option>
                      <option value="qurations">qurations</option>
             
                    </select>
                  </div>
                 
            </div>

            <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">course run</label>
                    <input class="form-control" type="number" name="course_year" maxlength="20" required placeholder="xxxx">
                  </div>
              </div>

            </div>
         
         
           <div class="row">
         

            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">author </label>
                   
                <select class="form-control" name="author"  required>
                  <option>-</option>
                  {% for usr in userlist %}
                  <option value="{{usr.id}}">{{usr.username}}</option>
                  {% endfor%}
                  
                 
                </select>
                </div>

                  
              </div>
            

            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label"> thumbnail</label>
                    <input class="form-control" type="file" name="image_course" required >
                  </div>

            </div>
           </div>
        
            <div class="tile-footer">
              <button class="btn btn-primary"  type="submit"><i class="bi bi-check-circle-fill me-2"></i>Create</button>&nbsp;&nbsp;&nbsp;<a class="btn btn-secondary" href="{% url 'course:course_view'%}"><i class="bi bi-x-circle-fill me-2"></i>Cancel</a>
            </div>
          </form>
        </div>
       
      </div>
    </div>
    

 
  </div>

  
{% endblock %}

course/templates/course_edit.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

 
  <div class="row">
    <div class="col-md-12">
      <div class="tile">
        <h3 class="tile-title">Create new course</h3>
        <div class="tile-body">
          <form id="sumbitformpratner" method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">course name</label>
                    <input class="form-control" type="text" name="course_name" value="{{ course.course_name }}" maxlength="250" required placeholder="Enter course name">
                  </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label"> topic</label>
                    <input class="form-control" type="text" name="topic" value="{{ course.topic}}" maxlength="250" required placeholder="Enter topic">
                  </div>
            </div>
           </div>
            <div class="row">
              <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">type course </label>
                   
                <select class="form-control" name="type_course"  required>
               
                
                 
                  <option value="{{ course.type_course }}" selected>{{ course.type_course}} </option>
                    
                  <option value="self">self</option>
                  <option value="instructor">instructor</option>

                
       



                </select>
                </div>

                  
              </div>
              <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">org </label>
                   
                <select class="form-control" name="org_partner" required>
                  

                  <option value="{{ course.org_partner.id }}" selected>{{ course.org_partner}} </option>

                  {% for part in partnerlist %}
                  <option value="{{part.id}}">{{part.partner_name}}</option>
                  {% endfor%}
                  
                 
                </select>
                </div>

                  
              </div>
            

              <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">status</label>
                    <select class="form-control" id="exampleSelect1" required name="status_course">
                     
                    <option value="{{ course.status_course }}" selected>{{ course.status_course}} </option>
                      <option value="draft">draft</option>
                    
                      <option value="pending">pending</option>
                      <option value="qurations">qurations</option>
             
                    </select>
                  </div>
                 
            </div>

            <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">course run</label>
                    <input class="form-control" type="number" name="course_year" value="{{course.course_year}}" maxlength="20" required placeholder="xxxx">
                  </div>
              </div>

            </div>
         
         
           <div class="row">
         

            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">author </label>
                   
                <select class="form-control" name="author"  required>
                  <option value="{{course.author.id}}">{{course.author}}</option>
                  
                  {% for usr in userlist %}
                  <option value="{{usr.id}}">{{usr.username}}</option>
                  {% endfor%}
                  
                 
                </select>
                </div>

                  
              </div>
            

            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label"> thumbnail</label>
                    {% if course.image_course %}
                    <img src="{{ course.image_course.url }}" alt="image here" style="width: 50px; height: 50px;">
                {% endif %}
                    <input class="form-control" type="file" name="image_course"  >
                  </div>

            </div>
           </div>
        
            <div class="tile-footer">
              <button class="btn btn-primary"  type="submit"><i class="bi bi-check-circle-fill me-2"></i>Register</button>&nbsp;&nbsp;&nbsp;<a class="btn btn-secondary" href="{% url 'partner:partner_view'%}"><i class="bi bi-x-circle-fill me-2"></i>Cancel</a>
            </div>
          </form>
        </div>
       
      </div>
    </div>
    

 
  </div>

  




  
{% endblock %}

course/templates/course_view.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}
<div class="col-md-12">
  <div class="tile">
    <div class="row">
      <div class="col-md-4">
    <h5 class="tile-title">{% trans 'table course' %}</h5>
  </div>
    <div class="col-md-8">
    <p style="text-align: right;"><a href="{% url 'course:course_add' %}" class="btn btn-primary" type="button"><i class="bi bi-check-circle-fill me-2"></i>{% trans 'Cretae New' %}</a></p>
  </div>
  </div>
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>{% trans 'course name' %}</th>
          <th>{% trans 'type' %} </th>
       
          <th>{% trans 'status' %}</th>
          <th>{% trans 'org' %}</th>
          <th>{% trans 'run' %}</th>
        </tr>
      </thead>
      <tbody>
        {% for part in courselist %}
        <tr>
          <td>1</td>
          <td><a href="{% url 'course:course_detail' part.id %}">{{part.course_name}}</a></td>
          <td>{{part.type_course}}</td>
          
          <td>
            {% if part.status_course == 'draft' %}
            <span class="badge text-bg-info">{% trans 'draft' %}</span>
            {% elif part.status_course == 'pending' %}
            <span class="badge text-bg-warning">{% trans 'pending' %}</span>
            {% elif part.status_course == 'publish' %}
            <span class="badge text-bg-success">{% trans 'publish' %}</span>
            {% else %}
            <span class="badge text-bg-primary">{% trans 'qurations' %}</span>
            {% endif %}
          </td>
          <td>{{part.org_partner}}</td>
          <td>{{part.course_year}}</td>
        </tr>
       {% endfor %}
      </tbody>
    </table>
  </div>
</div>
 





  
{% endblock %}