app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('partner/', include('partner.urls')),
    path('course/', include('course.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

partner/urls.py
from django.urls import path

from . import views

app_name = 'partner'

urlpatterns = [
    path("list/", views.partnerView, name= "partner_view"),
    path("partner-add/", views.partnerAdd, name= "partner_add"),
    path("partner-edit/<str:pk>", views.partnerEdit, name= "partner_edit"),

   
]

partner/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
import datetime
import os

def filepath(request, filename):
    old_filename = filename
    timeNow = datetime.datetime.now().strftime('%Y%m%d%H:%M:%S')
    filename = "%s%s" % (timeNow, old_filename)
    return os.path.join('uploads/', filename)

class Partner(models.Model):
    partner_name = models.TextField(max_length=191)
    abbreviation = models.CharField(max_length=50)
    e_mail = models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.CharField(max_length=50)
    address = models.TextField(max_length=50)
    tax = models.CharField(max_length=50)
    status = models.CharField(max_length=50)
    checks = models.CharField(max_length=50)
    logo = models.ImageField(upload_to=filepath,null=True, blank=True)
    join = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.partner_name}"

partner/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.conf import settings
from .models import Partner
from django.contrib import messages
from django.contrib.auth.models import User
import os

def partnerView(request):
     if request.user.is_staff == True:
           partner_list = Partner.objects.all()
           context = {'partnerlist':partner_list}   

           return render (request,'partner_view.html', context)
     else:
          
        return redirect ('/')

def partnerAdd(request):

    if request.user.is_staff == True:
        if request.method == "POST":
                par = Partner()
                par.partner_name = request.POST.get('partner_name')
                par.abbreviation = request.POST.get('partner_abbreviation')
                par.e_mail_id = request.POST.get('partner_email')
                par.phone = request.POST.get('partner_phone')
                par.address = request.POST.get('partner_address')
                par.tax = request.POST.get('partner_tax')
                par.status = request.POST.get('partner_status')
                #par.partner_logo = request.POST.get('partner_logo')
                par.checks = request.POST.get('partner_check')

                if len(request.FILES) != 0:
                    par.logo = request.FILES['partner_logo']
                    par.save()
                    messages.success(request, "PARTNER ADD SUCCESSFULLY")
                    return redirect('/partner/list')
        
        user_list = User.objects.all()
        context = {'us':user_list}
        return render (request,'partner_add.html', context)
    else:
        
        return redirect ('/')

# Create your views here.
def partnerEdit(request, pk):
    par = Partner.objects.get(id=pk)
    user_list = User.objects.all()
    if request.method == "POST":
        if len(request.FILES) != 0:
            if len(par.logo) > 0:
                os.remove(par.logo.path)
                 #prod.image = request.FILES['image']
            par.logo = request.FILES['partner_logo']
        par.partner_name = request.POST.get('partner_name')
        par.abbreviation = request.POST.get('partner_abbreviation')
        par.e_mail_id = request.POST.get('partner_email')
        par.phone = request.POST.get('partner_phone')
        par.address = request.POST.get('partner_address')
        par.tax = request.POST.get('partner_tax')
        par.status = request.POST.get('partner_status')
        
        par.checks = request.POST.get('partner_check')
        par.save()
        messages.success(request, "Product Updated Successfully")
        return redirect('/partner/list')

    context = {'partner':par,'user':user_list}
    return render(request, 'partner_edit.html', context)

partner/templates/partner_add.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

 
  <div class="row">
    <div class="col-md-12">
      <div class="tile">
        <h3 class="tile-title">Create new partner</h3>
        <div class="tile-body">
          <form id="sumbitformpratner" method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">name</label>
                    <input class="form-control" type="text" name="partner_name" maxlength="200" required placeholder="Enter full name">
                  </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label"> abbreviation</label>
                    <input class="form-control" type="text" name="partner_abbreviation" maxlength="50" required placeholder="Enter abbreviation">
                  </div>
            </div>
           </div>
            <div class="row">
              <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label ">email <span class="badge text-bg-info"> <a href=""> inactive</a></span></label>
                   
                <select class="form-control js-example-basic-single" name="partner_email"  required>
                  <option>select mail</option>
                  {% for uss in us %}
                  <option value="{{ uss.id }}">
                    {{ uss.email }}
                    
                  </option>
                  {% endfor%}
                </select>
                  </div>

                  
              </div>
              <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">phone</label>
                    <input class="form-control" type="number" name="partner_phone" maxlength="20" required placeholder="Enter phone address">
                  </div>
              </div>
            </div>
         
            <div class="mb-3">
              <label class="form-label">address</label>
              <textarea class="form-control" rows="4" name="partner_address" maxlength="200" required placeholder="Enter your address"></textarea>
            </div>
           <div class="row">
            <div class="col-md-4">
                <div class="mb-3">
                    <label class="form-label">tax  </label><small class="form-text text-muted"> max 50 %</small>
                    <input class="form-control" type="number" name="partner_tax" max="50" max="1" required placeholder="Enter tax">
                  </div>
            </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <label class="form-label">status</label>
                    <select class="form-control" id="exampleSelect1" required name="partner_status">
                      <option >select status</option>
                      <option value="1">active</option>
                      <option value="0">inactive</option>
                  
                    </select>
                  </div>
                 
            </div>

            <div class="col-md-4">
                <div class="mb-3">
                    <label class="form-label"> logo</label>
                    <input class="form-control" type="file" name="partner_logo" required >
                  </div>

            </div>
           </div>
            <div class="mb-3">
              <div class="form-check">
                <label class="form-check-label">
                  <input class="form-check-input" type="checkbox" name="partner_check" required>I accept the terms and send notif to the partner mail
                </label>
              </div>
            </div>
            <div class="tile-footer">
              <button class="btn btn-primary"  type="submit"><i class="bi bi-check-circle-fill me-2"></i>Register</button>&nbsp;&nbsp;&nbsp;<a class="btn btn-secondary" href="{% url 'partner:partner_view'%}"><i class="bi bi-x-circle-fill me-2"></i>Cancel</a>
            </div>
          </form>
        </div>
       
      </div>
    </div>
    

 
  </div>

  
{% endblock %}

partner/templates/partner_edit.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

 
  <div class="row">
    <div class="col-md-12">
      <div class="tile">
        <h3 class="tile-title">Update partner</h3>
        <div class="tile-body">
          <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">name</label>
                    <input class="form-control" type="text" name="partner_name" value="{{ partner.partner_name }}" maxlength="200" required placeholder="Enter full name">
                  </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label"> abbreviation</label>
                    <input class="form-control" type="text" name="partner_abbreviation" value="{{ partner.abbreviation }}" maxlength="50" required placeholder="Enter abbreviation">
                  </div>
            </div>
           </div>
            <div class="row">
              <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">email</label>
                    <select class="form-control js-example-basic-single" id="exampleSelect1"  required name="partner_email">
                       
                       
                      <option value="{{ partner.e_mail_id }}" selected>{{partner.e_mail.email}} </option>

                       

                        {% for us in user %} 
                        <option class="form-control" value="{{us.id}}">{{us.e_mail}}</option>
                       
                        {% endfor %}
             
                      </select>
                  </div>

                  
              </div>
              <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">phone</label>
                    <input class="form-control" type="number" name="partner_phone" value="{{ partner.phone }}" maxlength="20" required placeholder="Enter phone address">
                  </div>
              </div>
            </div>
         
            <div class="mb-3">
              <label class="form-label">address</label>
              <textarea class="form-control" rows="4" name="partner_address"  maxlength="200" required placeholder="Enter your address">{{ partner.address }}</textarea>
            </div>
           <div class="row">
            <div class="col-md-4">
                <div class="mb-3">
                    <label class="form-label">tax  </label><small class="form-text text-muted"> max 50 %</small>
                    <input class="form-control" type="number" name="partner_tax" value="{{ partner.tax }}" max="50" max="1" required placeholder="Enter tax">
                  </div>
            </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <label class="form-label">status</label>
                    <select class="form-control" id="exampleSelect1" value="{{ partner.status }}" required name="partner_status">
                      <option >select status</option>
                      <option value="1">active</option>
                      <option value="0">inactive</option>
                      {% if partner.status == '1' %}
                      <option value="{{ partner.status }}" selected>active</option>
                      {% else %}
                      <option value="{{ partner.status }}" selected>inactive</option>
                    {% endif%}
                    </select>
                  </div>
                 
            </div>

            <div class="col-md-4">
                <div class="mb-3">
                    <label class="form-label"> logo</label>
                    {% if partner.logo %}
                    <img src="{{ partner.logo.url }}" alt="image here" style="width: 50px; height: 50px;">
                {% endif %}
                    <input class="form-control" type="file" name="partner_logo"  >
                  </div>

            </div>
           </div>
            <div class="mb-3">
              <div class="form-check">
                <label class="form-check-label">
                  <input class="form-check-input" type="checkbox" checked name="partner_check" value="{{ partner.checks }}" required>I accept the terms and send notif to the partner mail
                </label>
              </div>
            </div>
            <div class="tile-footer">
              <button class="btn btn-warning"  type="submit"><i class="bi bi-check-circle-fill me-2"></i>update</button>&nbsp;&nbsp;&nbsp;<a class="btn btn-secondary" href="{% url 'partner:partner_view'%}"><i class="bi bi-x-circle-fill me-2"></i>Cancel</a>
            </div>
          </form>
        </div>
       
      </div>
    </div>
    

 
  </div>

  
{% endblock %}

partner/templates/partner_view.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}
<div class="col-md-12">
  <div class="tile">
    <div class="row">
      <div class="col-md-4">
    <h5 class="tile-title">{% trans 'table partner' %}</h5>
  </div>
    <div class="col-md-8">
    <p style="text-align: right;"><a href="{% url 'partner:partner_add' %}" class="btn btn-primary" type="button"><i class="bi bi-check-circle-fill me-2"></i>{% trans 'Register' %}</a></p>
  </div>
  </div>
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>{% trans 'name' %}</th>
          <th>{% trans 'email' %} </th>
          <th>{% trans 'phone' %}</th>
          <th>{% trans 'status' %}</th>
          <th>{% trans 'join' %}</th>
        </tr>
      </thead>
      <tbody>
        {% for part in partnerlist %}
        <tr>
          <td>1</td>
          <td><a href="{% url 'partner:partner_edit' part.id %}">{{part.partner_name}}</a></td>
          <td>{{part.e_mail}}</td>
          <td>{{part.phone}}</td>
          <td>
            {% if part.status == '1' %}
            <span class="badge text-bg-primary">{% trans 'active' %}</span>
            {% else %}
            <span class="badge text-bg-warning">{% trans 'inactive' %}</span>
            {% endif %}
          </td>
          <td>{{part.join}}</td>
        </tr>
       {% endfor %}
      </tbody>
    </table>
  </div>
</div>
 
  
{% endblock %}